.PHONY: build bundle clean run install lint validate-release-signing

BUILD_DIR = build
APP_BUNDLE = $(BUILD_DIR)/Swyper.app
BINARY = .build/release/Swyper
SPARKLE_FRAMEWORK = .build/release/Sparkle.framework
VERSION := $(shell cat VERSION)
DISPLAY_VERSION := $(VERSION)
BUNDLE_SHORT_VERSION := $(VERSION)
BUNDLE_VERSION := $(VERSION)
ifndef RELEASE
  DISPLAY_VERSION := $(VERSION)-dev.$(shell git rev-parse --short HEAD)
endif

# Code signing: CODESIGN_IDENTITY signs with an installed non-ad-hoc identity.
# For development builds without CODESIGN_IDENTITY, rcodesign with a self-signed
# certificate produces a stable designated requirement, falling back to ad-hoc.
CODESIGN_IDENTITY ?=
CODESIGN_IDENTITY_TRIMMED := $(strip $(CODESIGN_IDENTITY))
RCODESIGN := $(shell command -v rcodesign 2>/dev/null)
RCODESIGN_CERT := $(HOME)/.config/swyper/swyper-rcodesign.crt
RCODESIGN_KEY := $(HOME)/.config/swyper/swyper-rcodesign.key

validate-release-signing:
	@if [ -n "$(RELEASE)" ] && { [ -z "$(CODESIGN_IDENTITY_TRIMMED)" ] || [ "$(CODESIGN_IDENTITY_TRIMMED)" = "-" ]; }; then \
		echo "error: RELEASE=1 requires CODESIGN_IDENTITY to be an installed non-ad-hoc signing identity." >&2; \
		echo "       Example: make bundle RELEASE=1 CODESIGN_IDENTITY='Developer ID Application: Name (TEAMID)'" >&2; \
		exit 1; \
	fi

build:
	@echo '// Auto-generated by Makefile from VERSION file. Manual edits will be overwritten.' > Sources/Version.swift
	@echo 'let appVersion = "$(DISPLAY_VERSION)"' >> Sources/Version.swift
	swift build -c release

bundle: validate-release-signing build
	@mkdir -p "$(APP_BUNDLE)/Contents/MacOS"
	@mkdir -p "$(APP_BUNDLE)/Contents/Resources"
	@mkdir -p "$(APP_BUNDLE)/Contents/Frameworks"
	@cp $(BINARY) "$(APP_BUNDLE)/Contents/MacOS/Swyper"
	@cp Resources/Info.plist "$(APP_BUNDLE)/Contents/Info.plist"
	@plutil -replace CFBundleShortVersionString -string "$(BUNDLE_SHORT_VERSION)" "$(APP_BUNDLE)/Contents/Info.plist"
	@plutil -replace CFBundleVersion -string "$(BUNDLE_VERSION)" "$(APP_BUNDLE)/Contents/Info.plist"
	@cp Resources/AppIcon.icns "$(APP_BUNDLE)/Contents/Resources/"
	@cp -RP "$(SPARKLE_FRAMEWORK)" "$(APP_BUNDLE)/Contents/Frameworks/"
	@install_name_tool -add_rpath @executable_path/../Frameworks "$(APP_BUNDLE)/Contents/MacOS/Swyper" 2>/dev/null || true
ifneq ($(CODESIGN_IDENTITY_TRIMMED),)
ifeq ($(CODESIGN_IDENTITY_TRIMMED),-)
	@codesign --force --sign - --entitlements Swyper.entitlements "$(APP_BUNDLE)/Contents/MacOS/Swyper"
	@echo "Built $(APP_BUNDLE) (v$(DISPLAY_VERSION)) [ad-hoc signed]"
else
	@codesign --force --deep --sign "$(CODESIGN_IDENTITY)" --options runtime "$(APP_BUNDLE)/Contents/Frameworks/Sparkle.framework"
	@codesign --force --sign "$(CODESIGN_IDENTITY)" --options runtime --entitlements Swyper.entitlements "$(APP_BUNDLE)"
	@codesign --verify --deep --strict --verbose=2 "$(APP_BUNDLE)"
	@echo "Built $(APP_BUNDLE) (v$(DISPLAY_VERSION)) [signed with codesign: $(CODESIGN_IDENTITY)]"
endif
else ifneq ($(and $(RCODESIGN),$(wildcard $(RCODESIGN_CERT)),$(wildcard $(RCODESIGN_KEY))),)
	@rcodesign sign --pem-source "$(RCODESIGN_KEY)" --pem-source "$(RCODESIGN_CERT)" \
		--code-signature-flags runtime --entitlements-xml-path Swyper.entitlements "$(APP_BUNDLE)" >/dev/null
	@echo "Built $(APP_BUNDLE) (v$(DISPLAY_VERSION)) [signed with rcodesign]"
else
	@codesign --force --sign - --entitlements Swyper.entitlements "$(APP_BUNDLE)/Contents/MacOS/Swyper"
	@echo "Built $(APP_BUNDLE) (v$(DISPLAY_VERSION)) [ad-hoc signed]"
endif

run: bundle
	@open "$(APP_BUNDLE)"

install: bundle
	@cp -R "$(APP_BUNDLE)" /Applications/Swyper.app
	@echo "Installed to /Applications/Swyper.app"

lint:
	swiftlint

clean:
	swift package clean
	rm -rf $(BUILD_DIR)
